version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: license_finder
    versions:
    - 6.11.0
    - 6.12.1
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
  - dependency-name: rswag-ui
    versions:
    - 2.3.3
  - dependency-name: rswag-specs
    versions:
    - 2.3.3
  - dependency-name: rswag-api
    versions:
    - 2.3.3
  - dependency-name: database_cleaner-redis
    versions:
    - 2.0.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.445.0
    - 1.446.0
    - 1.448.0
    - 1.449.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.459.0
    - 1.462.0
    - 1.471.0
    - 1.474.0
    - 1.489.0
    - 1.505.0
    - 1.511.0
    - 1.521.0
    - 1.528.0
    - 1.530.0
    - 1.533.0
    - 1.538.0
    - 1.558.0
    - 1.566.0
    - 1.570.0
