# Development docker-compose file.
# Run with: docker-compose -f docker-compose.development.yml up
version: '3.7'

services:
  # PostgresSQL option.
  # db:
  #   image: 'postgres:12.2-alpine'
  #   volumes:
  #     - 'db:/var/lib/postgresql/data'
  #   env_file:
  #     - '.env'

  # MySQL option.
  db:
    image: 'mysql:8.0.22'
    restart: always
    volumes:
      - 'db:/var/lib/mysql'
    env_file:
      - '.env'
    ports:
      - '3307:3306'

  # SQL Server option.
  # db:
  #   image: microsoft/mssql-server-linux:2017-latest
  #   volumes:
  #     - 'db:/var/lib/sql_server'
  #   env_file:
  #     - '.env'
  #   ports:
  #     - '3307:1433'

  redis:
    image: 'redis:6.0.9-alpine'
    command: redis-server --requirepass yourpassword
    depends_on:
      - redis_helper
    sysctls:
      # This removes 'WARNING: /proc/sys/net/core/somaxconn is set to the lower value of 128'
      # Explanation of what this setting does: https://groups.google.com/d/msg/redis-db/ftmlTjEPv98/HwkJguxTCwAJ
      net.core.somaxconn: '511'
    volumes:
      - 'redis:/data'

  # Fix Redis 'WARNING you have Transparent Huge Pages (THP) support'.
  # From: https://stackoverflow.com/a/58090841
  # More details: https://easyengine.io/tutorials/redis/
  redis_helper:
    image: busybox:1.32.0
    command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    privileged: true

  api:
    depends_on:
      - db
      - redis
      - sidekiq
      - webpacker
    build: .
    command: ./script/start_rails.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      # We cache the bundle so that we don't re-download every gem on any change to the Gemfile.
      - bundle_cache:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - NODE_ENV=development
      - RAILS_ENV=development
    env_file:
      - '.env'

  bundle_cache:
    # BusyBox combines tiny versions of many common UNIX utilities into a single small executable.
    image: busybox:1.32.0
    volumes:
      - '.:/bundle_cache'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: ./script/start_sidekiq.sh
    volumes:
      - '.:/app'
      - bundle_cache:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - NODE_ENV=development
      - RAILS_ENV=development
    env_file:
      - '.env'

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - '.:/app'
      - bundle_cache:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - NODE_ENV=development
      - RAILS_ENV=development
    env_file:
      - '.env'

volumes:
  bundle_cache:
  redis:
  db:
