# Development docker-compose file.
# To use: docker-compose -f docker-compose.development.yml up
version: '3.7'

services:
  db:
    image: 'mysql:8.0.22'
    restart: always
    volumes:
      - 'db:/var/lib/mysql'
    env_file:
      - '.env'
    environment:
      - MYSQL_DATABASE=esr_api_development

  db_test:
    image: 'mysql:8.0.22'
    restart: always
    volumes:
      - 'db_test:/var/lib/mysql'
    env_file:
      - '.env'
    environment:
      - MYSQL_DATABASE=esr_api_test

  redis:
    image: 'redis:6.0.9-alpine'
    command: redis-server --requirepass yourpassword
    depends_on:
      - redis_helper
    sysctls:
      # This removes 'WARNING: /proc/sys/net/core/somaxconn is set to the lower value of 128'
      # Explanation of what this setting does: https://groups.google.com/d/msg/redis-db/ftmlTjEPv98/HwkJguxTCwAJ
      net.core.somaxconn: '511'
    volumes:
      - 'redis:/data'

  # Fix Redis 'WARNING you have Transparent Huge Pages (THP) support'.
  # From: https://stackoverflow.com/a/58090841
  # More details: https://easyengine.io/tutorials/redis/
  redis_helper:
    image: busybox:1.32.0
    command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    privileged: true

  rails:
    depends_on:
      - db
      - db_test
      - redis
      - sidekiq
      - webpacker
    build: .
    command: ./script/start_rails_development.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      # We cache the bundle so that we don't re-download every gem on any change to the Gemfile.
      - bundle_cache:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - NODE_ENV=development
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=1 # 1 is good for debugging.
      - WEB_CONCURRENCY=1 # 1 is good for debugging.
    env_file:
      - '.env'

  bundle_cache:
    # BusyBox combines tiny versions of many common UNIX utilities into a single small executable.
    image: busybox:1.32.0
    volumes:
      - '.:/bundle_cache'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: ./script/start_sidekiq.sh
    volumes:
      - '.:/app'
      - bundle_cache:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - NODE_ENV=development
      - RAILS_ENV=development
    env_file:
      - '.env'

  webpacker:
    build: .
    command: ./script/start_webpacker.sh
    ports:
      - '3035:3035'
    volumes:
      - '.:/app'
      - bundle_cache:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - NODE_ENV=development
      - RAILS_ENV=development
    env_file:
      - '.env'

volumes:
  bundle_cache:
  redis:
  db:
  db_test:
