# Production docker-compose file.
# Run with: docker-compose up
version: '3.7'

services:
  # MySQL option.
  db:
    image: 'mysql:8.0.22'
    restart: always
    volumes:
      - 'db:/var/lib/mysql'
    env_file:
      - '.env'
    restart: always

  redis:
    image: 'redis:6.0.9-alpine'
    command: redis-server --requirepass yourpassword
    depends_on:
      - redis_helper
    sysctls:
      # This removes 'WARNING: /proc/sys/net/core/somaxconn is set to the lower value of 128'
      # Explanation of what this setting does: https://groups.google.com/d/msg/redis-db/ftmlTjEPv98/HwkJguxTCwAJ
      net.core.somaxconn: '511'
    volumes:
      - 'redis:/data'
    restart: always

  # Fix Redis 'WARNING you have Transparent Huge Pages (THP) support'.
  # From: https://stackoverflow.com/a/58090841
  # More details: https://easyengine.io/tutorials/redis/
  redis_helper:
    image: busybox:1.32.0
    command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    privileged: true

  api:
    depends_on:
      - db
      - redis
      - sidekiq
    build: .
    command: ./script/start_rails.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - NODE_ENV=production
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5 # See config/puma.rb for more info.
      - WEB_CONCURRENCY=2 # See config/puma.rb for more info.
    env_file:
      - '.env'
    restart: always

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: ./script/start_sidekiq.sh
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    env_file:
      - '.env'
    restart: always

volumes:
  redis:
  db:
