---

default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  reconnect: false
  pool: 50
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
  socket: /var/run/mysqld/mysqlx.sock

development:
  <<: *default
  database: esr_api_development

test:
  <<: *default
  database: esr_api_test

staging:
  <<: *default
  database: esr_api_test

production:
  <% if ENV['CLEARDB_DATABASE_URL'] %>
    # For Heroku.
    adapter: mysql2
    encoding: utf8mb4
    database: esr_api_production
    url: <%= ENV['CLEARDB_DATABASE_URL'] %>
  <% else %>
    <<: *default
    database: esr_api_production
  <% end %>
